# Generated by Django 2.1.7 on 2019-04-30 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('num_cols', models.IntegerField()),
                ('num_rows', models.IntegerField()),
                ('num_well', models.IntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.IntegerField()),
                ('length', models.IntegerField()),
                ('sequence', models.CharField(blank=True, max_length=10000)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('pos_i', models.IntegerField()),
                ('pos_j', models.IntegerField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concentration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Plate')),
                ('samples', models.ManyToManyField(to='db.Sample')),
            ],
            options={
                'ordering': ('name', 'plate'),
            },
        ),
    ]
