# Generated by Django 2.1.9 on 2019-08-06 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='direction',
            field=models.CharField(blank=True, choices=[('FWD', 'Forward'), ('REV', 'Reverse')], max_length=3),
        ),
        migrations.AlterField(
            model_name='sample',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.Sample'),
        ),
        migrations.AlterField(
            model_name='well',
            name='parent_well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.Well'),
        ),
    ]
