# Generated by Django 2.1.9 on 2019-08-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20190806_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='comments',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
