# Generated by Django 2.1.11 on 2019-08-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20190807_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='sub_sample_id',
        ),
        migrations.AddField(
            model_name='sample',
            name='sub_sample_id',
            field=models.ManyToManyField(related_name='child_sample', to='db.Sample'),
        ),
    ]
