# Generated by Django 2.1.11 on 2019-08-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20190812_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sub_sample_id',
            field=models.ManyToManyField(blank=True, related_name='subsample', to='db.Sample'),
        ),
    ]
