# Generated by Django 2.1.11 on 2019-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20190812_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='organism',
            field=models.CharField(blank=True, choices=[('Human', 'Human'), ('Yeast', 'Yeast')], max_length=1),
        ),
    ]
