# Generated by Django 2.1.11 on 2019-08-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20190813_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='source_reference',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
