# Generated by Django 2.1.11 on 2019-10-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20190813_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='part_type',
            field=models.CharField(blank=True, choices=[('Promoter', 'Promoter'), ('Terminator', 'Terminator'), ('CDS', 'CDS'), ('Connector_R', 'Connector_R'), ('Connector_L', 'Connector_L'), ('Backbone', 'Backbone'), ('Counter_Screen', 'Counter_Screen'), ('Marker', 'Marker'), ('Miscellaneous', 'Miscellaneous')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='project',
            field=models.CharField(blank=True, choices=[('GF_General', 'GF_General'), ('Sanguinarine', 'Sanguinarine'), ('MoClo_Kit', 'MoClo_Kit'), ('Yeast_CRISPR_Kit', 'Yeast_CRISPR_Kit'), ('Foundry_Kit', 'Foundry_Kit')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(choices=[('Primer', 'Primer'), ('Plasmid', 'Plasmid'), ('Part', 'Part'), ('Linker', 'Linker'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
