# Generated by Django 2.1.11 on 2019-10-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_auto_20191004_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='part_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
