# Generated by Django 2.1.11 on 2019-10-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20191009_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Accuri', 'Accuri'), ('Sunrise', 'Sunrise'), ('TapeStation', 'TapeStation'), ('Echo', 'Echo'), ('QPix', 'QPix'), ('Biomek', 'Biomek'), ('Mantis', 'Mantis'), ('QuBit', 'QuBit'), ('Chromium', 'Chromium'), ('MultiFlow', 'MultiFlow'), ('Fragment_analyzer', 'Fragment_analyzer'), ('ViiA7', 'ViiA7'), ('inSPIRE', 'inSPIRE')], default='Accuri', max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
