# Generated by Django 2.1.11 on 2019-10-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='comments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Not working', 'Not working')], default='Working', max_length=50),
        ),
    ]
