# Generated by Django 2.1.11 on 2019-10-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_auto_20191011_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image',
            field=models.ImageField(blank=True, max_length=10000, upload_to='pics/'),
        ),
    ]
