# Generated by Django 2.1.11 on 2019-10-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_machine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='image',
            field=models.ImageField(blank=True, max_length=10000, upload_to='pics'),
        ),
    ]
