# Generated by Django 2.1.11 on 2019-11-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_auto_20191121_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='plate',
            name='project',
            field=models.ManyToManyField(to='db.Project'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='project',
            field=models.ManyToManyField(to='db.Project'),
        ),
    ]
