# Generated by Django 2.1.11 on 2019-11-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0031_auto_20191125_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='file',
            field=models.FileField(blank=True, max_length=10000, upload_to='design/'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='project',
            field=models.ManyToManyField(blank=True, to='db.Project'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='project',
            field=models.ManyToManyField(blank=True, to='db.Project'),
        ),
    ]
