# Generated by Django 2.1.11 on 2019-11-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0032_auto_20191127_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='file',
        ),
        migrations.AddField(
            model_name='plate',
            name='file',
            field=models.FileField(blank=True, max_length=10000, upload_to='design/'),
        ),
    ]
