# Generated by Django 2.1.11 on 2019-08-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0011_auto_20190813_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('input', models.ManyToManyField(blank=True, related_name='input_plates', to='db.Plate')),
                ('output', models.ManyToManyField(blank=True, related_name='output_plates', to='db.Plate')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='workflow',
            field=models.ManyToManyField(blank=True, to='design.Step'),
        ),
    ]
