# Generated by Django 2.1.11 on 2019-09-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='instrument',
            field=models.CharField(blank=True, choices=[('Echo', 'Echo'), ('Mantis', 'Mantis'), ('Biomek', 'Biomek'), ('QIAquick96', 'QIAquick96'), ('Qpix', 'Qpix'), ('Thermal Cycler', 'Thermal Cycler'), ('Fragment Analyzer', 'Fragment Analyzer')], max_length=30),
        ),
        migrations.AddField(
            model_name='step',
            name='script',
            field=models.CharField(blank=True, choices=[('Moclo', 'Moclo'), ('Normalization', 'Normalization'), ('Spotting', 'Spotting')], max_length=30),
        ),
    ]
