# Generated by Django 2.1.11 on 2019-09-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20190903_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='input_file',
            field=models.FileField(blank=True, max_length=10000, upload_to='design/'),
        ),
    ]
