# Generated by Django 2.1.11 on 2019-09-23 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_experiment_input_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='workflow',
        ),
        migrations.AddField(
            model_name='step',
            name='experiment',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='design.Experiment'),
        ),
    ]
