# Generated by Django 2.1.11 on 2019-09-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_auto_20190923_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='status_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='project',
            field=models.CharField(blank=True, choices=[('GF', 'GF_general'), ('SA', 'Sanguinarine'), ('MK', 'MoClo kit'), ('YK', 'Yeast CRISPR kit')], max_length=100),
        ),
    ]
