# Generated by Django 2.1.11 on 2019-10-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(choices=[('Accuri', 'Accuri'), ('Sunrise', 'Sunrise'), ('TapeStation', 'TapeStation'), ('Echo', 'Echo'), ('QPix', 'QPix'), ('Biomek', 'Biomek'), ('Mantis', 'Mantis'), ('QuBit', 'QuBit'), ('Chromium', 'Chromium'), ('MultiFlow', 'MultiFlow'), ('Fragment_analyzer', 'Fragment_analyzer'), ('ViiA7', 'ViiA7'), ('inSPIRE', 'inSPIRE')], default='Accuri', max_length=100)),
                ('user', models.CharField(max_length=30)),
                ('supervisor', models.CharField(max_length=100)),
                ('time_used', models.TimeField()),
                ('comments', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
