# Generated by Django 2.1.11 on 2019-10-11 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Machine'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='user',
            field=models.CharField(default='', max_length=30),
        ),
    ]
