# Generated by Django 2.1.11 on 2019-10-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_auto_20191011_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='time_used',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
